import { PDFTool } from '../types';

export const PDF_TOOLS: PDFTool[] = [
  {
    id: 'merge',
    name: 'Merge PDF',
    description: 'Combine multiple PDF files into a single document in any order.',
    category: 'organize',
    longDescription: 'Merge or combine multiple PDF files into one file. Drag-and-drop to reorder, view page previews, and download instantly.',
    iconName: 'GitMerge',
    isBrowserSide: true,
    priority: 1,
  },
  {
    id: 'split',
    name: 'Split PDF',
    description: 'Extract specific page ranges or split each page into a separate PDF.',
    category: 'organize',
    longDescription: 'Extract specific ranges of pages (e.g., 1-5, 6-10) or save every single page as a separate PDF document.',
    iconName: 'Scissors',
    isBrowserSide: true,
    priority: 2,
  },
  {
    id: 'organize',
    name: 'Organize Pages',
    description: 'Rotate, delete, reorder, or duplicate pages in a visual grid.',
    category: 'organize',
    longDescription: 'Manage your PDF page-by-page. Reorder pages via drag-and-drop, rotate pages by 90-degree steps, duplicate, or delete unneeded pages visually.',
    iconName: 'Layers',
    isBrowserSide: true,
    priority: 3,
  },
  {
    id: 'compress',
    name: 'Compress PDF',
    description: 'Reduce file size while preserving maximum quality levels.',
    category: 'utility',
    longDescription: 'Optimize and shrink the size of your PDF files inside your browser. Select from 4 compression levels targeting screens, ebooks, or production printing.',
    iconName: 'Heading1', // will map to Minimize2
    isBrowserSide: true,
    priority: 4,
  },
  {
    id: 'edit',
    name: 'Edit PDF Pages',
    description: 'Annotate PDF walls with texts, shapes, freehand drawing, and highlights.',
    category: 'edit',
    longDescription: 'Draw freehand shapes, highlight paragraphs, insert solid shapes (rectangles, circles), or type text boxes directly over rendered document pages with undo/redo steps.',
    iconName: 'Edit3',
    isBrowserSide: true,
    priority: 5,
  },
  {
    id: 'sign',
    name: 'Sign PDF',
    description: 'Fill forms or place transparent digital signatures on any page.',
    category: 'edit',
    longDescription: 'Create custom transparent signatures by typing cursive fonts, drawing via mouse/touch screen, or uploading a photo. Stamp and resize signatures anywhere.',
    iconName: 'Signature', // will map to PenTool
    isBrowserSide: true,
    priority: 6,
  },
  {
    id: 'convert-from',
    name: 'All-in-One PDF Extraction',
    description: 'Deconstruct PDF pages to select and run any format conversions.',
    category: 'convert',
    longDescription: 'Deconstruct a PDF file from your device, extracting embedded images, raw text files, or rendering individual sheets out as separate graphics.',
    iconName: 'FileText',
    isBrowserSide: true,
    priority: 7,
  },
  {
    id: 'convert-to',
    name: 'All-in-One Doc to PDF',
    description: 'Compile multiple office formats or photo collections to PDF documents.',
    category: 'convert',
    longDescription: 'Convert a list of images or documents into a single fully aligned PDF. Specify page sizes, margins, and download instantly.',
    iconName: 'FileImage',
    isBrowserSide: true,
    priority: 8,
  },
  {
    id: 'pdf-docx',
    name: 'PDF to Word (DOCX)',
    description: 'Convert PDF layouts and sentences into Microsoft Word paragraph files.',
    category: 'convert',
    longDescription: 'Extract formatted document sheets and tables from PDF structures directly into Microsoft Word DOCX formats.',
    iconName: 'FileEdit',
    isBrowserSide: true,
    priority: 81,
  },
  {
    id: 'pdf-xlsx',
    name: 'PDF to Excel (XLSX)',
    description: 'Extract multi-column sheets and spreadsheet cells to Excel workbooks.',
    category: 'convert',
    longDescription: 'Parse row lists and cell grids from standard PDF catalogs into fully separated Microsoft Excel XLSX spreadsheet structures.',
    iconName: 'Grid',
    isBrowserSide: true,
    priority: 82,
  },
  {
    id: 'pdf-pptx',
    name: 'PDF to PowerPoint (PPTX)',
    description: 'Format page chapters into widescreen presentation outline slide frames.',
    category: 'convert',
    longDescription: 'Translate separate page outlines and headers into widescreen standard presentation PPTX outlines.',
    iconName: 'Presentation',
    isBrowserSide: true,
    priority: 83,
  },
  {
    id: 'pdf-image',
    name: 'PDF to JPG / PNG',
    description: 'Render document pages into high-resolution JPG or PNG graphic formats.',
    category: 'convert',
    longDescription: 'Generate pixel-perfect image snapshots for pages in high-contrast lossless PNG or compact JPG layouts.',
    iconName: 'FileImage',
    isBrowserSide: true,
    priority: 84,
  },
  {
    id: 'pdf-html',
    name: 'PDF to HTML',
    description: 'Create responsive web standards layouts styled with modern CSS.',
    category: 'convert',
    longDescription: 'Extract block components from standard digital documents to fully unified HTML markup sheets.',
    iconName: 'FileCode',
    isBrowserSide: true,
    priority: 85,
  },
  {
    id: 'pdf-txt',
    name: 'PDF to Plain Text',
    description: 'Deconstruct raw searchable unicode texts without margins.',
    category: 'convert',
    longDescription: 'Isolate text strings from vector streams and render clean unicode files (.txt).',
    iconName: 'FileText',
    isBrowserSide: true,
    priority: 86,
  },
  {
    id: 'pdf-epub',
    name: 'PDF to EPUB',
    description: 'Pack articles into standard digital book formats for eBook readers.',
    category: 'convert',
    longDescription: 'Generate flowing digital books (.epub) from page texts, optimized for reader displays.',
    iconName: 'BookOpen',
    isBrowserSide: true,
    priority: 87,
  },
  {
    id: 'pdf-csv',
    name: 'PDF to CSV',
    description: 'Extract tabular financial transactions and records to CSV files.',
    category: 'convert',
    longDescription: 'Detect row boundaries and cells automatically, compiling them as comma separated values.',
    iconName: 'Grid',
    isBrowserSide: true,
    priority: 88,
  },
  {
    id: 'docx-pdf',
    name: 'Word to PDF',
    description: 'Compile Microsoft Word (.docx or .doc) templates to secure PDF files.',
    category: 'convert',
    longDescription: 'Parse headings and text paragraphs from Word files directly to formatted electronic document sheets.',
    iconName: 'FileEdit',
    isBrowserSide: true,
    priority: 89,
  },
  {
    id: 'xlsx-pdf',
    name: 'Excel to PDF',
    description: 'Compile spreadsheets and ledger rows directly to PDF ledgers.',
    category: 'convert',
    longDescription: 'Render multi-column spreadsheet records into neat vector documents inside your browser.',
    iconName: 'Grid',
    isBrowserSide: true,
    priority: 90,
  },
  {
    id: 'pptx-pdf',
    name: 'PowerPoint to PDF',
    description: 'Compile active presentation slide decks (.pptx) to PDF sheets.',
    category: 'convert',
    longDescription: 'Translate presentation slides and outlines in sequence to vector PDF frames.',
    iconName: 'Presentation',
    isBrowserSide: true,
    priority: 91,
  },
  {
    id: 'image-pdf',
    name: 'JPG/PNG to PDF',
    description: 'Combine multiple screenshots and photos as a single printable record.',
    category: 'convert',
    longDescription: 'Merge collections of JPG, PNG, or GIF screenshots on A4 canvas sheets instantly.',
    iconName: 'FileImage',
    isBrowserSide: true,
    priority: 92,
  },
  {
    id: 'html-pdf',
    name: 'HTML to PDF',
    description: 'Render web structural layouts and CSS sheets directly as PDFs.',
    category: 'convert',
    longDescription: 'Convert responsive raw HTML websites or files into print-ready PDF formats.',
    iconName: 'FileCode',
    isBrowserSide: true,
    priority: 93,
  },
  {
    id: 'md-pdf',
    name: 'Markdown to PDF',
    description: 'Compile plain text markdown (.md) documents to formatted reports.',
    category: 'convert',
    longDescription: 'Assemble structured markdown syntax elements (headings, bullet lists) directly as document structures.',
    iconName: 'Sparkles',
    isBrowserSide: true,
    priority: 94,
  },
  {
    id: 'protect',
    name: 'Protect PDF',
    description: 'Encrypt files with strong standard passwords and permission flags.',
    category: 'security',
    longDescription: 'Encrypt your PDF. Set open passwords, permissions, or configure encryption tags to secure sensitive legal documents.',
    iconName: 'Lock',
    isBrowserSide: true,
    priority: 95,
  },
  {
    id: 'repair',
    name: 'Repair PDF',
    description: 'Recover and reconstruct corrupt or unreadable PDF document layouts.',
    category: 'utility',
    longDescription: 'Optimize and reconstruct corrupted or broken PDF streams. Automatically clean object indexes, repair headers, and recover pages in the browser.',
    iconName: 'Wrench',
    isBrowserSide: true,
    priority: 10,
  },
  {
    id: 'ocr',
    name: 'OCR Text Extractor',
    description: 'Perform visual OCR and extract plain searchable text outlines in seconds.',
    category: 'utility',
    longDescription: 'Extract raw selectable text structures, table blocks, or handwriting grids from images or scanned PDF layers without uploading files.',
    iconName: 'ScanText',
    isBrowserSide: true,
    priority: 11,
  }
];
